export const data=[
    {
        id:1,
        name:'kathakali',
        heading:'Kathakali',
        img:'Kathakali (1).jpg',
        description:'Classical Dance-Drama of Kerala',
        detail:'The name Kathakali came into being through the joining of two words, Katha (story) and kali (Kala/art). The dance uses Attakatha (plays derived from Hindu epics). There are seven fundamental make-up codes to depict different ragas (emotions) which is the major essence of this dance form.',
        orgin:'Orgin: Kerala',
        uniquefactor:'Unique factor: Intricate and vivid make-up, unique face masks and costumes',
        keyexponents:'Key exponents: Kavungal Chathunni Panicker, Kalamandalam Gopi, Kottakkal Sivaraman, Kalamandalam Ramankutty Nair, Kalamandalam Krishna Prasad, Kalamandalam Vasu Pisharody, Kalamandalam Kesavan Namboodiri, and Kalanilayam Balakrishnan',
    },
    {
        id:2,
        name:'odissi',
        heading:'odissi',
        img:'odissi-dance-768x685.jpg',
        description:'Classical Dance of Orissa',
        detail:'Kavichandra Kalicharan Pattanayak is hugely responsible for the revival of this dance form and for naming it Odissi. Its theoretical origins are in Natya Shastra, the ancient Sanskrit text on performing arts. It is related to the ritual dance in northern temples in ancient India. This dance form starts with an invocation called Mangalacharana which is then followed by Pushpanjali, which is an offering of flowers. This is followed by Bhumi Pranam. The sequence followed then is nritta, nritya, natya, and moksha. It is now regional dance form of Orissa.',
        orgin:'Origin: Odisha ',
        uniquefactor:'Unique factor: Includes ragas from North as well as South India. ',
        keyexponents:'Key exponents: Kelucharan Mohapatra, Raghunath Dutta, Deba Prasad Das, Pankaj Charan Das, and Gangadhar Pradhan',
    },
    {
        id:3,
        name:'Gaudiya Nritya',
        heading:'Gaudiya Nrity',
        img:'gaudiya_nritya-dance.jpg',
        description:'Bengali Dance Tradition',
        detail:'This is one of the oldest forms of classical Indian dance. Mahua Mukherjee reconstructed this dance form and worked for its revival. This dance has a lot of circular movements. There is a balanced mix of rigid and flexible elements.',
        orgin:'Origin: Gauda/Gaur, in Bengal.',
        uniquefactor:'Unique factor: Revived after almost becoming extinct in the 20th century due to lack of patronage',
        keyexponents:'Key exponents: Mahua Mukherjee, Arpita Mukherjee, Rachel Priyanka Perris',
    },
    {
        id:4,
        name:'Yakshagana',
        heading:'Yakshagana',
        img:'yakshagana.png',
        description:'Classical Dance-Drama of Kerala',
        detail:'The word Yakshgana means the songs of the Demi-Gods. The performance includes dance and drama with poetic songs led by Bhagavata, the chief musician. Male performers play both male and female characters. Most performances of this dance take place between the months of November and May.',
        orgin:'Origin: Dakshina Kannada and Uttara Kannada districts, in the state of Karnataka and Kasaragod district in Keral',
        uniquefactor:'Unique factor: Traditionally impromptu dialogues, making each performance unique',
        keyexponents:'Key exponents</b>: Keremane Shivarama Heggade, Dr. Prabhakar Joshi, Hudagodu Chandrahasa',
    },
    {
        id:5,
        name:'Bharatanatyam',
        heading:'Bharatanatyam',
        img:'Bharatnatyam.jpg',
        description:'The Oldest Dance Form Of India',
        detail:'Bharatanatyam is supposedly the oldest form of Indian classical dances and is considered the mother dance to many other forms. Bharatanatyam, the name is formed from two words Bharata and Natyam. Natyam means dance in Sanskrit, while Bharata is a mnemonic denoting of emotions with melody, and rhythm.',
        orgin:'Origin: Hindu temples of Tamil Nadu',
        uniquefactor:'Unique factor: All intricate details are codified, analyzed and preserved for perfection ',
        keyexponents:'',
    },
    {
        id:6,
        name:'Theyyam',
        heading:'Theyyam',
        img:'theyyam.jpg',
        description:'The Oldest Dance Form Of India',
        detail:'Theyyams are Hindu ritualistic dance forms practiced in northern Kerala and some parts of Karnataka. Theyyam is also known as Kaḷiyāṭṭaṁ or Tiṟa. Theyyam consists of traditions, rituals and customs associated with temples and sacred groves of Malabar.[1] The people of the region consider Theyyam itself as a channel to a god and they thus seek blessings from Theyyam.',
        orgin:'Origin: Kerala ',
        uniquefactor:'Unique factor:  This ritual art is mainly performed in the kavus (temples) or ancestral houses of Nambiar, Thiyyar, Vaniyar and Maniyani communities.',
        keyexponents:'Key exponents: Kelucharan Mohapatra, Raghunath Dutta, Deba Prasad Das, Pankaj Charan Das, and Gangadhar Pradhan.',
    },
    {
        id:7,
        name:'Kuchipudi',
        heading:'Kuchipudi',
        img:'Kuchipudi-768x512.jpg',
        description:'A Dance-Drama Performance',
        detail:'Kuchipudi involves remarkable footwork, impressive eye movements, thespian characterization, and energetic narrative. It combines tandava and lasya elements. People take 2-7 years to master this art form.',
        orgin:'Origin:  Krishna district of Andhra Pradesh ',
        uniquefactor:'Unique factor: Execution on a brass plate and moving the plate to the accompaniment of Carnatic music',
        keyexponents:'Key exponents: Indrani Bajpai, Raja and Radha Reddy, Yamini Reddy, Kaushalya Reddy, Bhavana Reddy, Lakshmi Narayn Shastri; and Swapana Sundari',
    },
    {
        id:8,
        name:'Ottamthullal',
        heading:'Ottamthullal',
        img:'fnb979.jpg',
        description:'A recite-and-dance artform. ',
        detail:'ottamthullal is a recite-and-dance art-form of Kerala, India. It was introduced in the eighteenth century by Kunchan Nambiar, one of the Prachina Kavithrayam (three famous Malayalam-language poets). The folksy performance, often laced with humour intended at criticism of society, is accompanied by a mridangam (a barrel-shaped double-headed drum) and/or the handy idakka besides a pair of ilathalam cymbals.',
        orgin:'Origin: kerala ',
        uniquefactor:'Unique factor:  Ottamthullal has its principles influenced by the Natya Shastra.',
        keyexponents:'Key exponents:  It was introduced in the eighteenth century by Kunchan Nambiar',
    },
    {
        id:9,
        name:'Manipuri',
        heading:'Manipuri',
        img:'Manipuri-Dance-768x483.jpg',
        description:'A recite-and-dance artform. ',
        detail:'Earlier, the name of this dance was Jogai (circular movement). The themes included under this dance are Vaishnavism, Ras Lila, Shaktism, Shaivism, and on the sylvan deities called Umang Lai. This dance form is performed at Hindu festivals and special occasions like marriage.',
        orgin:'Origin: Manipur ',
        uniquefactor:'Unique factor: Team performance with unique costumes, major emphasis on upper body movements. ',
        keyexponents:'Key exponents: Guru Bipin Singh, Darshana Jhaveri, Nayana, Ranjana and Suverna, Charu Mathur and Devyani Chalia.',
    },
    {
        id:10,
        name:'Sattriya',
        heading:'Sattriya',
        img:'Sattriya-Dance-768x510.jpg',
        description:'Classical Dance of Assam ',
        detail:'The name Sattriya comes from Satra (monastery). This dance has evolved, and now has a well-structured pattern that is transmitted through the Gurukul system. Mati-Akhora is the base of this dance form. Sattriya, in its original form, is a male tradition, performed by bhokots (male monks) in monasteries. The main theme of this dance is Krishna and Radha, displaying the passionate emotions that they hold.',
        orgin:'Origin: Assam ',
        uniquefactor:'Unique factor: Distinctive footwork patterns and intricate costumes ',
        keyexponents:'Key exponents:Indira PP Bora, Maniram Datta Moktar',
    },
    {
        id:11,
        name:'Kathak',
        heading:'Kathak',
        img:'Kathak-280x300.jpg',
        description:'A recite-and-dance artform. ',
        detail:'Kathak is one of the main types of Indian classical dance. The dancers narrate a Katha (as the word itself says story) through their intricate movements. These stories include Hindu mythological legends, especially ones about the life of Krishna. The three main sections of the dance are an invocation, Nritta, and Nritya. There are three gharanas (schools) of this dance. These are Jaipur gharana, Benaras gharana, and Lucknow gharana.',
        orgin:'Origin:  Banaras/Varanasi ',
        uniquefactor:'Unique factor: Conveyance of stories through the foot, hand and eye movements as well as facial expressions ',
        keyexponents:'Key exponents: Bhanuji, Janaki Prasad, Ishwari Prasad, Sitara Devi,  Raja Chakradhar Singh, Shambhu Maharaj, Lachhu Maharaj, and Acchan Maharaj.',
    },
    {
        id:12,
        name:'Mohiniattam',
        heading:'Mohiniattam',
        img:'Mohiniattam.jpg',
        description:'Dance Of The Women Of Kerala',
        detail:'The name of this dance form comes from the word Mohini (the female avatar of Vishnu). This dance form has a legend attached to it. Mohiniattam is a graceful and feminine form of dance adhering to the Lasya element. It is a solo female dance performed to a Manipravala (Malayalam and Sanskrit) song.',
        orgin:'Origin: Kerala',
        uniquefactor:'Unique factor: 40 different basic movements called Adavukal',
        keyexponents:'Key exponents: Vallathol Narayana Menon, Kalamandalam Kalyanikutty Amma, Thankamony, Krishna Panicker, Mukundraja, Sunanda Nair; Smitha Rajan, Radha Dutta, Vijayalakshmi, Gopika Varma and Jayaprabha Menon.',
    },
]
